products = [
  {
    '_id': '1',
    'name': 'Oven-Roasted Beef Brisket With Caramelised',
    'image': '/images/meat.jpg',
    'description':
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s.',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 25.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Venezuelan HOTDOGS - Double Bacon',
    'image': '/images/hotdog.jpg',
    'description':
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 7.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Hamburger "Big XXL Bacon-Cheese',
    'image': '/images/fastfood.jpg',
    'description':
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    'brand': 'Nesti',
    'category': 'Fast Food',
    'price': 16.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'Mediterranean fried fish - French',
    'image': '/images/fish.jpg',
    'description':
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    'brand': 'Sony',
    'category': 'Electronics',
    'price': 20.55,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'The best pancakes - American Pancakes',
    'image': '/images/pancakes.jpg',
    'description':
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 12.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Rustic Iron Italian Pizza Dough',
    'image': '/images/pizza.jpg',
    'description':
      'Viandes 1/2 cup Italian sausage, cooked and crumbled spicy Fruits et légumes1 Basil, Fresh leaves Condiments 1/4 cup Black olives 1/2 cup Marinara sauce, homemade or store-bought Aides culinaires et épices 2 cups All-purpose flour 1/2 tsp Instant yeast 2 tsp Italian seasoning 1 tsp Salt 1 tsp Sugar',
    'brand': 'Amazon',
    'category': 'Electronics',
    'price': 10.25,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
  },
]
